### ISSUE TITLE
API: Teams in a district/District Ranking

### ISSUE THREAD

**Issue by flyingcow93** [the-blue-alliance/the-blue-alliance#1162]
More of a request rather then an issue, currently you can grab /api/v2/district/<district>/<year>/rankings which generates a list of teams that have played at least one event in the district. This causes some issues:

-If a team goes out of district, they are now included in the other district as well (Example: 3314 (MAR) went to NE in 2015.)
-Teams that have not played a district yet are not listed at all, so a 'list of teams in x district in y year' list cannot be built.
-Events also seem to return in a random order, it would be nice if they were ordered either chronologically, or a week value was also returned for the event, or a 'play' value (1st play, 2nd play, 3rd play, would be nice so we could ignore 3rd plays), or all of the above were implemented.

I'm a bit new to figuring out how github works, but more then happy to help figure out a solution if someone could point me in the right direction.

**Comment by flyingcow93** [comment]
Not exactly related to above but I'm trying to follow along with the readme to setup everything on my pc, having trouble with the 'paver setup' command. Says its missing a file, but doesn't specify which file as far as I can tell. Heres the output:

C:\Users\Brandon>cd C:\Users\Brandon\Dropbox\tba git\the-blue-alliance

C:\Users\Brandon\Dropbox\tba git\the-blue-alliance>paver setup
---> pavement.setup
---> pavement.make
---> pavement.javascript
Combining and Compressing Javascript
python do_compress.py js
Compressing Main JavaScript...
 + static/jwplayer/jwplayer.js
 + static/xcharts/d3.v2.min.js
 + static/xcharts/xcharts.min.js
 + static/javascript/tba_js/tablesorter.js
 + static/javascript/tba_js/tba_charts.js
 + static/javascript/tba_js/tba_countdown.js
 + static/javascript/tba_js/tba_sidebar.js
 + static/javascript/tba_js/tba_typeahead.js
 + static/javascript/tba_js/tba.js
=> static/javascript/tba_combined_js.main.min.js
Original: 303.81 kB
Compressed: 298.35 kB
Reduction: 1.8%

Compressing GameDay JavaScript...
 + static/jwplayer/jwplayer.js
 + static/xcharts/d3.v2.min.js
 + static/xcharts/xcharts.min.js
 + static/javascript/tba_js/tablesorter.js
 + static/javascript/tba_js/tba_charts.js
 + static/javascript/tba_js/tba_countdown.js
 + static/javascript/tba_js/tba_sidebar.js
 + static/javascript/tba_js/tba_typeahead.js
 + static/javascript/tba_js/tba.js
 + static/javascript/tba_js/gameday.js
 + static/javascript/tba_js/gameday_twitter.js
 + static/javascript/tba_js/gameday_matchbar.js
 + static/javascript/tba_js/gameday_ticker.js
 + static/javascript/tba_js/gameday_mytba.js
=> static/javascript/tba_combined_js.gameday.min.js
Original: 342.49 kB
Compressed: 322.41 kB
Reduction: 5.9%

---> pavement.less
Building and Combining CSS
lessc static/css/less_css/tba_style.main.less static/css/less_css/tba_style.main
.css
lessc static/css/less_css/tba_style.gameday.less static/css/less_css/tba_style.g
ameday.css
python do_compress.py css
Compressing Main CSS...
 + static/css/precompiled_css/jquery.fancybox.css
 + static/css/precompiled_css/tablesorter.css
 + static/xcharts/xcharts.min.css
 + static/css/less_css/tba_style.main.css
=> static/css/tba_combined_style.main.min.css
Original: 169.47 kB
Compressed: 134.98 kB
Reduction: 20.4%

Compressing GameDay CSS...
 + static/css/precompiled_css/jquery.fancybox.css
 + static/css/precompiled_css/tablesorter.css
 + static/css/less_css/tba_style.gameday.css
=> static/css/tba_combined_style.gameday.min.css
Original: 173.31 kB
Compressed: 137.32 kB
Reduction: 20.8%



Captured Task Output:
---------------------

---> pavement.setup
---> pavement.make
---> pavement.javascript
python do_compress.py js
---> pavement.less
lessc static/css/less_css/tba_style.main.less static/css/less_css/tba_style.main
.css
lessc static/css/less_css/tba_style.gameday.less static/css/less_css/tba_style.g
ameday.css
python do_compress.py css
Traceback (most recent call last):
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 196, in _run_task
    return do_task()
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 60, in setup
    setup_function()
  File "pavement.py", line 87, in setup_function
    make()
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 321, in __call__
    retval = environment._run_task(self.name, self.needs, self.func)
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 214, in _run_task
    return do_task()
  File "E:\Programs\python\lib\site-packages\paver-1.2.4-py2.7.egg\paver\tasks.p
y", line 193, in do_task
    return func(**kw)
  File "pavement.py", line 40, in make
    git_branch_name = subprocess.check_output(["git", "rev-parse", "--abbrev-ref
", "HEAD"])
  File "E:\Programs\python\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "E:\Programs\python\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "E:\Programs\python\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified


C:\Users\Brandon\Dropbox\tba git\the-blue-alliance>

**Comment by phil-lopreiato** [comment]
The main issue with the feature request is the difficulty of determining the geographic boundaries of where a team's "home district" is. That will add complexity in finding teams that have not yet competed and removing teams who "live" in a different district. This isn't data FIRST gives us (while the district an event belongs to is).

The sorting of events is easily doable

**Comment by flyingcow93** [comment]
sorting them would be a start. Maybe a team list for each district could be scraped from http://frc-districtrankings.usfirst.org/ as they are listed on their regardless of if they've played an event yet

**Comment by phil-lopreiato** [comment]
I submitted a [feature request](https://usfirst.collab.net/sf/go/artf4059?nav=1&_pagenum=1&returnUrlKey=1428357976588) for the FRCAPI for district data. Hopefully that will be implemented before next season

**Comment by fangeugene** [comment]
The team endpoint from FRCAPI does give the district is associated with. We currently have no way of storing this in our DB, which I want to avoid doing.

Is there a way to programatically determine what district a team is part of for a given year? For example, if a team attends 2 events from district A and 1 event from district B, they must be in district A. Is a team allowed to attend more than 1 district outside of their own?

**Comment by phil-lopreiato** [comment]
The [blog post](http://www.usfirst.org/roboticsprograms/frc/blog-inter-district-play-for-2015)  does not give an upper limit on the number of out-of-district plays a team can have. Although every team is guaranteed at least two in their home district. 

Maybe we just need a task that runs after second event registration loses, where every team is only signed up for their home events

**Comment by bdaroz** [comment]
Thinking about APIv3, and the `/district/{key}/{year}/teams` endpoint, this sounds like it would make more sense to pull the data from the DistrictTeam model rather than walk the events in the district for the given year. The same (v2) data could be obtained by the client walking the v3 `/district/{key}/{year}/events` endpoint. Worth thinking about in #1507.
