### ISSUE TITLE
Errors attempting to send notifications

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1287]
```
E 2015-11-24 19:20:03.937  500     176 B   37 ms E 19:20:03.972 /tasks/notifications/upcoming_match
  0.1.0.1 - - [24/Nov/2015:19:20:03 -0800] "GET /tasks/notifications/upcoming_match HTTP/1.1" 500 176 - "AppEngine-Google; (+http://code.google.com/appengine)" "tbatv-prod-hrd.appspot.com" ms=37 cpu_ms=11 cpm_usd=1.9668999999999998e-05 instance=00c61b117c6af62a624fbf2643302d1969a1294d app_engine_release=1.9.29 trace_id=-
    E 19:20:03.972 Expected string, got []
      Traceback (most recent call last):
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
          rv = self.handle_exception(request, response, e)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
          rv = self.router.dispatch(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
          return route.handler_adapter(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
          return handler.dispatch()
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
          return self.handle_exception(e, self.app.debug)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
          return method(*args, **kwargs)
        File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.388761874871547643/controllers/cron_controller.py", line 456, in get
          NotificationHelper.send_upcoming_matches(live_events)
        File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.388761874871547643/helpers/notification_helper.py", line 113, in send_upcoming_matches
          status_sitevar.values_json = down_events
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1383, in __set__
          self._set_value(entity, value)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1128, in _set_value
          value = self._do_validate(value)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1075, in _do_validate
          value = self._call_shallow_validation(value)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1267, in _call_shallow_validation
          return call(value)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1314, in call
          newvalue = method(self, value)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 1764, in _validate
          (value,))
      BadValueError: Expected string, got []
```

**Comment by phil-lopreiato** [comment]
Aww shoot, I guess #1268 wasn't totally ready. I'll fix this one
