### ISSUE TITLE
template not found errors on Jan 8

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1331]
There are a lot of template not found errors from a Yahoo bot crawl on 1/8/16

```
E 2016-01-08 21:45:23.588  500     225 B  802 ms E 21:45:24.389 /event/2015hiho
  108.162.215.115 - - [08/Jan/2016:21:45:23 -0800] "GET /event/2015hiho HTTP/1.1" 500 225 - "Mozilla/5.0 (Linux; Android 5.1.1; SM-G920T Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.83 Mobile Safari/537.36" "www.thebluealliance.com" ms=802 cpu_ms=634 cpm_usd=2.5144999999999997e-05 instance=00c61b117c7256679f032792e67af15b3a06e626 app_engine_release=1.9.30 trace_id=-
    E 21:45:24.389 event_details.html
      Traceback (most recent call last):
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
          rv = self.handle_exception(request, response, e)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
          rv = self.router.dispatch(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
          return route.handler_adapter(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
          return handler.dispatch()
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
          return self.handle_exception(e, self.app.debug)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
          return method(*args, **kwargs)
        File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.389853369562061266/controllers/event_controller.py", line 106, in get
          super(EventDetail, self).get(event_key)
        File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.389853369562061266/controllers/base_controller.py", line 54, in get
          rendered = self._render(*args, **kw)
        File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.389853369562061266/controllers/event_controller.py", line 171, in _render
          return jinja2_engine.render('event_details.html', self.template_values)
        File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.389853369562061266/template_engine/jinja2_engine.py", line 37, in render
          template = JINJA_ENV.get_template(template)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 719, in get_template
          return self._load_template(name, self.make_globals(globals))
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 693, in _load_template
          template = self.loader.load(self, name, globals)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/loaders.py", line 443, in load
          raise TemplateNotFound(name)
      TemplateNotFound: event_details.html
```

These are all the same errors

![image](https://cloud.githubusercontent.com/assets/57101/12216875/70bb826e-b6a4-11e5-9eb9-5fbadf49fbf5.png)

**Comment by fangeugene** [comment]
Er. Was this after you deployed? `paver make` does more things now.

**Comment by gregmarra** [comment]
This was after I deployed. I did a paver preflight though, and these pages are loading for me now?

**Comment by fangeugene** [comment]
They seem to be. I deployed sometime yesterday after my last commit.

**Comment by gregmarra** [comment]
What would paver make be not doing right anymore?

**Comment by fangeugene** [comment]
Make sure you have jinja2 installed

**Comment by fangeugene** [comment]
`paver jinja2` should create `templates_jinja2_compiled.zip` in the root directory.

**Comment by gregmarra** [comment]
I have jinja2 installed, and that step ran. My deploy directory has `templates_jijna2_compiled.zip` in it. Is that all templates, or just the ones you've switched to use jinja?

**Comment by fangeugene** [comment]
Just the ones i've switched. Event and team details, mostly.

**Comment by gregmarra** [comment]
Oh, which are the ones that were erroring >.<

**Comment by fangeugene** [comment]
They stop erroring around the time I last deployed. So something is funny with your deploy it seems.

**Comment by gregmarra** [comment]
Hmm. My deploy steps are:

* Switch to a separate checkout I have
* `git pull`
* edit `app.yaml` and `dispatch.yaml` to be tba-prod-hrd
* paver preflight
* check all tests pass
* deploy with GoogleAppEngineUploader

**Comment by fangeugene** [comment]
Oh, right, you can't use the GUI. Also, you don't have to change stuff to
"tba-prod-hrd" if you run the following in the folder:

    # Update default module and other YAMLs
    python "C:/Program Files (x86)/Google/google_appengine/appcfg.py" -A
tbatv-prod-hrd update . (don't forget the .)
    # Update other modules
    python "C:/Program Files (x86)/Google/google_appengine/appcfg.py" -A
tbatv-prod-hrd update app-backend-tasks.yaml

**Comment by gregmarra** [comment]
Ok, I think what we need to do is get the deploy script working so it can work easily on any system. I've got to stop using the GUI and start using the deploy script.

**Comment by synth3tk** [comment]
Tracking separately in #1333.

**Comment by gregmarra** [comment]
Closing this since we know #1333 is the problem.
