### ISSUE TITLE
Exceptions in mobile_main.py prevent app from starting up on new dev instance

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1385]
These Exceptions prevent the app from starting up on instances that don't have the Sitevar `appengine.webClientId` or `android.clientId` defined, which by definition a fresh dev instance cannot.

https://github.com/the-blue-alliance/the-blue-alliance/blob/master/mobile_main.py#L29
https://github.com/the-blue-alliance/the-blue-alliance/blob/master/mobile_main.py#L35

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~tbatv-dev-hrd/1-3.391106452951212864/mobile_main.py", line 29, in <module>
    raise Exception("Sitevar appengine.webClientId is undefined. Can't process incoming requests")
Exception: Sitevar appengine.webClientId is undefined. Can't process incoming requests
```

These need to not throw Exceptions, and instead log warnings and gracefully handle not sending notifications.

**Comment by gregmarra** [comment]
These probably don't prevent the app from starting, digging a bit deeper with Eugene. We probably should catch them somewhere though.

**Comment by phil-lopreiato** [comment]
That's a good point, this should probably be handled better
