### ISSUE TITLE
Team pages 500ing

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1565]
https://www.thebluealliance.com/team/5202/2016
https://www.thebluealliance.com/team/4550
https://www.thebluealliance.com/team/1982/2014

**Comment by gregmarra** [comment]
Cloud monitoring caught that this morning and alerted #monitoring in slack.

![image](https://cloud.githubusercontent.com/assets/57101/17086767/7ae93d20-51af-11e6-8cea-b56b59d59843.png)

**Comment by gregmarra** [comment]
A stack trace for a /history URL:

```
team_history.html
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/team_controller.py", line 145, in get
    super(TeamHistory, self).get(team_number)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/base_controller.py", line 58, in get
    rendered = self._render(*args, **kw)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/team_controller.py", line 152, in _render
    return TeamRenderer.render_team_history(self, team, False)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/renderers/team_renderer.py", line 191, in render_team_history
    return jinja2_engine.render('team_history.html', handler.template_values)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/template_engine/jinja2_engine.py", line 37, in render
    template = JINJA_ENV.get_template(template)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 719, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 693, in _load_template
    template = self.loader.load(self, name, globals)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/loaders.py", line 443, in load
    raise TemplateNotFound(name)
TemplateNotFound: team_history.html
```

**Comment by gregmarra** [comment]
A stack trace for a team year page
```
team_details.html
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/team_controller.py", line 115, in get
    super(TeamDetail, self).get(team_number, year)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/base_controller.py", line 58, in get
    rendered = self._render(*args, **kw)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/team_controller.py", line 122, in _render
    rendered_result = TeamRenderer.render_team_details(self, team, int(year), False)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/renderers/team_renderer.py", line 143, in render_team_details
    return jinja2_engine.render('team_details.html', handler.template_values)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/template_engine/jinja2_engine.py", line 37, in render
    template = JINJA_ENV.get_template(template)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 719, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 693, in _load_template
    template = self.loader.load(self, name, globals)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/loaders.py", line 443, in load
    raise TemplateNotFound(name)
TemplateNotFound: team_details.html
```

**Comment by gregmarra** [comment]
Matches are also 500ing.

```
match_details.html
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/match_controller.py", line 28, in get
    super(MatchDetail, self).get(match_key)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/base_controller.py", line 58, in get
    rendered = self._render(*args, **kw)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/controllers/match_controller.py", line 55, in _render
    return jinja2_engine.render('match_details.html', self.template_values)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-3.394438245133337945/template_engine/jinja2_engine.py", line 37, in render
    template = JINJA_ENV.get_template(template)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 719, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/environment.py", line 693, in _load_template
    template = self.loader.load(self, name, globals)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/jinja2-2.6/jinja2/loaders.py", line 443, in load
    raise TemplateNotFound(name)
TemplateNotFound: match_details.html
```

**Comment by gregmarra** [comment]
Root cause seems almost certainly finding Jinja2 templates.

**Comment by gregmarra** [comment]
Last push information:
```
Build time: Sun Jul 24 17:47:32 2016
Branch: master
Commit: 3825c6cc16fa0509f0b474ea87864d72e4555ac3
Merge: 9820629 fabc636
Author: Eugene Fang <fang.eugene@gmail.com>
Date: Sun Jul 24 14:24:52 2016 -0400
```

**Comment by gregmarra** [comment]
What would have changed about our Jinja configuration between July 24th and today when these issues started?

**Comment by gregmarra** [comment]
@fangeugene pushed this afternoon, but it didn't update the admin message. Perhaps something was bad with his build / push. He currently doesn't have electrical power.

**Comment by phil-lopreiato** [comment]
Nothing seems strange about the most recent diff, it could be possible something was up with the jinja build step? Anyone else set up to push the site? (we should really work on our bus factor)

**Comment by gregmarra** [comment]
I'm going to test deploying to a dev server

**Comment by phil-lopreiato** [comment]
I was able to deploy master, which seems to have resolved this issue. I was able to load the pages in OP with no issues.
![screenshot from 2016-07-24 19-39-54](https://cloud.githubusercontent.com/assets/2754863/17087423/6915cc4e-51d7-11e6-847a-8fad4cd9c300.png)

**Comment by gregmarra** [comment]
Chart confirms errors are back down to 0:

![image](https://cloud.githubusercontent.com/assets/57101/17089708/2039d892-51de-11e6-83f3-ab3623656aaa.png)
