### ISSUE TITLE
Gulp issues on OS X

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1566]
I'm not able to get gulp to work with npm on OS X

After installing a clean version of Node 5, I get 
```
[➜  the-blue-alliance git:(master) gulp   
module.js:341
    throw err;
    ^

Error: Cannot find module './lib/cloneBuffer'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gregmarra/codez/the-blue-alliance/node_modules/vinyl-source-stream/node_modules/vinyl/index.js:4:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by phil-lopreiato** [comment]
I can't reproduce these gulp issues on my MBP? Any insight, @gregmarra?

```
➜  lopreiato@lopreiato-mbp the-blue-alliance git:(master) gulp -v
[16:42:31] CLI version 3.9.1
[16:42:31] Local version 3.9.1
```

**Comment by gregmarra** [comment]
Can you post your mode and npm versions too?

**Comment by phil-lopreiato** [comment]
```
➜  lopreiato@lopreiato-mbp the-blue-alliance git:(master) node --version
v6.1.0
➜  lopreiato@lopreiato-mbp the-blue-alliance git:(master) npm --version
3.8.6
```
