### ISSUE TITLE
pep8 issues on OS X

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1567]
```
➜  the-blue-alliance git:(master) paver lint
---> pavement.lint
python linter.py
Traceback (most recent call last):
  File "/usr/local/bin/pep8", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pep8==1.4.6
```

Do we require a specific version of pep8?

**Comment by gregmarra** [comment]
`easy_install pep8==1.4.6` fixed this
