### ISSUE TITLE
NameError: global name 'gcm_post_json_str' is not defined

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1604]
```
global name 'gcm_post_json_str' is not defined
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 310, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 305, in run_from_request
    run(self.request.body)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 147, in run
    return func(*args, **kwds)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 190, in invoke_member
    return getattr(obj, membername)(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395023401602409566/notifications/base_notification.py", line 88, in render
    NotificationSender.send_webhook(notification, self.keys[ClientType.WEBHOOK])
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395023401602409566/helpers/notification_sender.py", line 45, in send_webhook
    logging.warning('400, Invalid message: ' + repr(gcm_post_json_str))
NameError: global name 'gcm_post_json_str' is not defined
```

**Comment by ZachOrr** [comment]
Oh wow this is fixed already 🙆‍♂ https://github.com/the-blue-alliance/the-blue-alliance/issues/1712
