### ISSUE TITLE
Admin bar breaks Gameday

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1626]
Repro steps:
1/ Be an admin
2/ Go to Gameday
3/ 500

```
'ascii' codec can't encode character u'\xbb' in position 7780: ordinal not in range(128)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395810031254956386/controllers/base_controller.py", line 74, in get
    self.response.out.write(self._add_admin_bar(rendered))
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395810031254956386/controllers/base_controller.py", line 62, in _add_admin_bar
    return re.sub(r'<!-- Admin Bar -->', admin_bar, html.decode('utf-8'))
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 7780: ordinal not in range(128)
```

**Comment by fangeugene** [comment]
I know it doesnt work as expected. :(

**Comment by nwalters512** [comment]
It works with GD2 :stuck_out_tongue:
