### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#1637]
Happens when `alliance['picks']` doesn't have all 3 teams.

```
list index out of range (/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395992419827879332/controllers/api/api_base_controller.py:76)
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395992419827879332/controllers/api/api_base_controller.py", line 86, in get
    super(ApiBaseController, self).get(*args, **kw)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395992419827879332/controllers/base_controller.py", line 72, in get
    rendered = self._render(*args, **kw)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395992419827879332/controllers/api/api_event_controller.py", line 178, in _render
    points = DistrictHelper.calculate_event_points(self.event)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395992419827879332/helpers/district_helper.py", line 73, in calculate_event_points
    selection_points = EventHelper.alliance_selections_to_points(event.key_name, POINTS_MULTIPLIER, event.alliance_selections)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.395992419827879332/helpers/event_helper.py", line 46, in alliance_selections_to_points
    team_points[alliance['picks'][1]] = (17 - n) * multiplier
IndexError: list index out of range
```

**Comment by bdaroz** [comment]
Closing as likely resolved in the Py4 migration and/or hasn't recurred.
