### ISSUE TITLE
Errors trying to delete team media

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#1645]
```
11:30:19.206
POST
500
225 B
246 ms
Chrome 53
/admin/media/delete_reference/youtube_wCPln562l4U?list=PLG3YxINAL_ELP6qKROW3H_rq16Z0tHrPS
 108.162.237.184 - greg.marra [16/Oct/2016:11:30:19 -0400] "POST /admin/media/delete_reference/youtube_wCPln562l4U?list=PLG3YxINAL_ELP6qKROW3H_rq16Z0tHrPS HTTP/1.1" 500 225 http://www.thebluealliance.com/admin/team/4481 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "www.thebluealliance.com" ms=246 cpu_ms=132 cpm_usd=2.5144999999999998e-8 loading_request=0 instance=00c61b117c28fabddf14b153ea5d23dd1ee6a6c52d05f1e9cc863b42811b8e app_engine_release=1.9.45 trace_id=-
{
 metadata: {…}   
 protoPayload: {…}   
 insertId: "2016-10-16|08:30:24.246577-07|10.106.187.130|-1274136853"   
 log: "appengine.googleapis.com/request_log"   
 httpRequest: {…}   
 operation: {…}   
}
11:30:19.448
'NoneType' object has no attribute 'references'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.396202355348832974/controllers/admin/admin_media_controller.py", line 35, in post
    media.references.remove(media.create_reference(
AttributeError: 'NoneType' object has no attribute 'references'
```

Deleting because

```
I am a member of Team Rembrandts 4481. I would like to ask if it is possible that you remove some video's links on the Team Rembrandts pages.

These video's are no longer online.
```

Went to http://www.thebluealliance.com/admin/team/4481 and started deleting references with broken YT embeds. Started hitting errors after a few.

**Comment by gregmarra** [comment]
I'm probably trying to delete the same video twice, but we could fail without a 500.

**Comment by fangeugene** [comment]
Yeah it looks like you were deleting the same video twice. I'll fix it so it doesn't 500.
