### ISSUE TITLE
Test FRC API Match Tiebreaker Tests Failing

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#2089]
test_2017flwp_sequence (test_fms_api_match_tiebreaker.TestFMSAPIMatchTiebreaker)  started failing randomly. Currently affecting all new PRs like #2087 and #2088 

## Current Behavior
```
======================================================================
ERROR: test_2017flwp_sequence (test_fms_api_match_tiebreaker.TestFMSAPIMatchTiebreaker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/the-blue-alliance/the-blue-alliance/tests/test_fms_api_match_tiebreaker.py", line 51, in test_2017flwp_sequence
    MatchManipulator.createOrUpdate(DatafeedFMSAPI('v2.0', sim_time=query_time).getMatches('2017{}'.format(event_code)), run_post_update_hook=False)
  File "/home/travis/build/the-blue-alliance/the-blue-alliance/datafeeds/datafeed_fms_api.py", line 283, in getMatches
    qual_matches = qual_matches_future.get_result()
  File "/home/travis/google_appengine/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/home/travis/google_appengine/google/appengine/ext/ndb/tasklets.py", line 430, in _help_tasklet_along
    value = gen.send(val)
  File "/home/travis/build/the-blue-alliance/the-blue-alliance/datafeeds/datafeed_fms_api.py", line 159, in _parse_async
    for item in json.loads(result.content)['items']:
KeyError: 'items'
```

**Comment by fangeugene** [comment]
Seems to work again...
