### ISSUE TITLE
2018 Avatars page too big for memcache

### ISSUE THREAD

**Issue by fangeugene** [the-blue-alliance/the-blue-alliance#2112]
```
Values may not be more than 1000000 bytes in length; received 1068828 bytes (/base/data/home/apps/s~tbatv-prod-hrd/prod-1.407850019439231351/controllers/main_controller.py:50)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.407850019439231351/controllers/base_controller.py", line 81, in get
    self._write_cache(self.response)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-1.407850019439231351/controllers/base_controller.py", line 139, in _write_cache
    memcache.set(self.cache_key, compressed, self._get_cache_expiration())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/1/google/appengine/api/memcache/__init__.py", line 780, in set
    MemcacheSetRequest.SET, key, value, time=time, namespace=namespace)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/1/google/appengine/api/memcache/__init__.py", line 885, in _set_with_policy
    namespace)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/1/google/appengine/api/memcache/__init__.py", line 973, in _set_multi_async_with_policy
    stored_value, flags = _validate_encode_value(value, self._do_pickle)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/1/google/appengine/api/memcache/__init__.py", line 239, in _validate_encode_value
    'received %d bytes' % (MAX_VALUE_SIZE, len(stored_value)))
ValueError: Values may not be more than 1000000 bytes in length; received 1068828 bytes
```

**Comment by fangeugene** [comment]
Closed in #2120
