### ISSUE TITLE
TBANS tests failing due to new year

### ISSUE THREAD

**Issue by andrewda** [the-blue-alliance/the-blue-alliance#2635]
It's 2020! :tada: But that means that the TBANS tests which were hard-coded for events like `2019testpresent` are now failing, as they now have an ID of `2020testpresent`.

```
======================================================================
FAIL: test_data_payload (tbans_tests.models.notifications.test_match_score.TestMatchScoreNotification)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tba/tests/tbans_tests/models/notifications/test_match_score.py", line 64, in test_data_payload
    self.assertEqual(payload['event_key'], '2019testpresent')
AssertionError: u'2020testpresent' != '2019testpresent'

======================================================================
FAIL: test_webhook_message_data (tbans_tests.models.notifications.test_match_score.TestMatchScoreNotification)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tba/tests/tbans_tests/models/notifications/test_match_score.py", line 71, in test_webhook_message_data
    self.assertEqual(payload['event_key'], '2019testpresent')
AssertionError: u'2020testpresent' != '2019testpresent'
```

It looks like the only usages of these year-specific events will be removed in #2621. In the meantime, the fix should just be:

```bash
$ find . -type f -exec sed -i 's/2019testpresent/2020testpresent/g' {} \;
```

**Comment by ZachOrr** [comment]
Fixed by https://github.com/the-blue-alliance/the-blue-alliance/pull/2639
