### ISSUE TITLE
WebOb 1.2 deprecation error

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#2761]
We're seeing a new error specifically when fetching Team@Event for `/api/v3/team/{team_key}/event/2020cadm/status`

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 273, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1499, in __call__
    with self.request_context_class(self, environ) as (request, response):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1383, in __enter__
    request = self.app.request_class(self.environ)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 130, in __init__
    super(Request, self).__init__(environ, *args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/api:prod-2.425070506937771331/lib/webob/request.py", line 130, in __init__
    "req.decode(charset)``" % charset
DeprecationWarning: You passed charset='iso-8859-1' to the Request constructor. As of WebOb 1.2, if your application needs a non-UTF-8 request charset, please construct the request without a charset or with a charset of 'None',  then use ``req = req.decode(charset)``
```

My guess is some underlying dependency got bumped that wasn't pinned

**Comment by ZachOrr** [comment]
Hmm our `webob` version hasn't changed for quite some time (we have an indirect dependency, v1.8.6 is getting pulled in). It also looks like for quite some time our deploys have been using `google_appengine_1.9.66`. That version is fairly old, but I feel like we would've seen this issue before now.

Also interestingly, we stopped seeing this error at `3/6/20, 3:27 PM` - I'm unsure what would've changed since then on our end. I'm going to close this out, and mark this as resolved on the backend so we get notified if this pops up again.
