### ISSUE TITLE
TBANS._send_fcm `Failed to parse batch request, error:  0 items`

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#2766]
Probably just need a check to make sure we're not sending zero items when doing a batch send to FCM (which I thought we did but I guess not)

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 155, in run
    return func(*args, **kwds)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/1ce24fb0dd935902/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 198, in invoke_member
    return getattr(obj, membername)(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/backend-tasks:prod-2.425100228923800068/helpers/tbans_helper.py", line 412, in _send_fcm
    batch_response = fcm_request.send()
  File "/base/data/home/apps/s~tbatv-prod-hrd/backend-tasks:prod-2.425100228923800068/models/notifications/requests/fcm_request.py", line 47, in send
    response = messaging.send_multicast(self._fcm_message(), app=self._app)
  File "/base/data/home/apps/s~tbatv-prod-hrd/backend-tasks:prod-2.425100228923800068/lib/firebase_admin/messaging.py", line 168, in send_multicast
    return _get_messaging_service(app).send_all(messages, dry_run)
  File "/base/data/home/apps/s~tbatv-prod-hrd/backend-tasks:prod-2.425100228923800068/lib/firebase_admin/messaging.py", line 391, in send_all
    raise self._handle_batch_error(error)
InvalidArgumentError: Failed to parse batch request, error:  0 items. Received batch body: 
```

**Comment by ZachOrr** [comment]
This LOC looks like the problem - I'm not sure how I'd get an empty array from this though. Maybe it's an empty `client.messaging_id`?
