### ISSUE TITLE
global name 'bigquery' is not defined

### ISSUE THREAD

**Issue by ZachOrr** [the-blue-alliance/the-blue-alliance#3216]
Our backup tasks are throwing 500s. We were unable to figure out what changed - one day we started getting a lot of BigQuery errors. Inspecting the logs, it didn't look like the library changed from underneath us.

```
global name 'bigquery' is not defined (/base/alloc/tmpfs/dynamic_runtimes/python27g/dd89b7af809b5e76/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py:1528)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/dd89b7af809b5e76/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/dd89b7af809b5e76/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/dd89b7af809b5e76/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/dd89b7af809b5e76/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/dd89b7af809b5e76/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/dd89b7af809b5e76/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/prod-2.431416439108923187/controllers/backup_controller.py", line 294, in get
    bigquery_client = bigquery.Client()
NameError: global name 'bigquery' is not defined
```

**Comment by ZachOrr** [comment]
Related - we added logging to try to track down the BigQuery import issue, but we're not seeing these print logs upstream

**Comment by ZachOrr** [comment]
Oh kidding - it looks like we have logs

```
bigquery import failed: The 'google-cloud-bigquery' distribution was not found and is required by the application (/base/data/home/apps/s~tbatv-prod-hrd/prod-2.431416439108923187/controllers/backup_controller.py:31)
```

**Comment by bdaroz** [comment]
Removing stale, related to #1387 -- last CSV backup was ~7 years ago and would be a good idea to have.
