### ISSUE TITLE
2023 Avatars page 500s

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#4988]
Chrome on iOS 500s at https://www.thebluealliance.com/avatars/2023

**Comment by fangeugene** [comment]
```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/workspace/backend/common/decorators.py", line 31, in decorated_function
    resp = make_response(cached(func)(*args, **kwargs))
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask_caching/__init__.py", line 404, in decorated_function
    rv = self._call_fn(f, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask_caching/__init__.py", line 180, in _call_fn
    return ensure_sync(fn)(*args, **kwargs)
  File "/workspace/backend/web/handlers/index.py", line 222, in avatar_list
    avatars = sorted(
  File "/workspace/backend/web/handlers/index.py", line 223, in <lambda>
    avatars_future.get_result(), key=lambda a: int(a.references[0].id()[3:])
IndexError: list index out of range
```

**Comment by fangeugene** [comment]
`a.references` should be non-empty. I wonder why it's erroring. Unless it's the `[3:]` part that's erroring?

**Comment by fangeugene** [comment]
I found a malformed entry with empty references. time to explore why.
