### ISSUE TITLE
500 on /tasks/get/usfirst_event_details/2013/9009

### ISSUE THREAD

**Issue by gregmarra** [the-blue-alliance/the-blue-alliance#534]
```
2013-03-16 14:23:44.779 /tasks/get/usfirst_event_details/2013/9009 500 1398ms 0kb AppEngine-Google; (+http://code.google.com/appengine)
0.1.0.2 - - [16/Mar/2013:14:23:44 -0700] "GET /tasks/get/usfirst_event_details/2013/9009 HTTP/1.1" 500 176 "http://tbatv-prod-hrd.appspot.com/tasks/enqueue/usfirst_event_details/2013" "AppEngine-Google; (+http://code.google.com/appengine)" "tbatv-prod-hrd.appspot.com" ms=1398 cpu_ms=210 cpm_usd=0.000105 queue_name=usfirst task_name=15173396621283603929 instance=00c61b117c85b748a1bc571330ba1d330a4444
E 2013-03-16 14:23:44.549
'Team' object is not iterable
Traceback (most recent call last):
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tbatv-prod-hrd/1-2.365967434684608297/controllers/datafeed_controller.py", line 163, in get
    for team in teams]
TypeError: 'Team' object is not iterable
```

**Comment by gregmarra** [comment]
Going to close, too old.
