### ISSUE TITLE
Uploading FMS event rankings silently fails

### ISSUE THREAD

**Issue by brianjmaher** [the-blue-alliance/the-blue-alliance#6597]
## Expected Behavior
When a user with write credentials uploads the FMS ranking Excel export, the UI should respond in a way that indicates the file was either successfully or unsuccessfully uploaded.

## Current Behavior
When uploading [this Excel file](https://docs.google.com/spreadsheets/d/1EjlMksoBfB6ueGdCYsyu9HryeCxghiPK/edit?usp=sharing&ouid=107534650849534091966&rtpof=true&sd=true), the web UI shows the file name but no other feedback. The following is logged in the browser console:
```
jquery.min.js:3 [Deprecation] Listener added for a 'DOMSubtreeModified' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.

eventwizard:1 Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.success (tba_combined_js.even…zard.min.js:1:15672)
    at j (jquery.min.js:2:26911)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:27724)
    at x (jquery.min.js:4:11065)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4:14577)
tba_combined_js.eventwizard.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at reader.onload (tba_combined_js.even…zard.min.js:1:10809)
www.facebook.com/aja…YArXmDNd612KfsPX2:1 
 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
tba_combined_js.eventwizard.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at HTMLInputElement.<anonymous> (tba_combined_js.even…izard.min.js:1:9661)
    at HTMLInputElement.dispatch (jquery.min.js:3:6444)
    at r.handle (jquery.min.js:3:3219)
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by bdaroz** [comment]
Eventwizard was recently reworked, and this is likely fixed by #8489 - if not, please reopen the issue and we'll investigate.
